//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCountdown.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_ID
    {
        public int ProjectId { get; set; }
        public string NameoFProject { get; set; }
        public string DescriptionOfProject { get; set; }
        public string LinktoGithub { get; set; }
        public Nullable<int> ScreenshotID { get; set; }
    
        public virtual ScreenshotsOfProject ScreenshotsOfProject { get; set; }
    }
}
